server:
  port: 8080

spring:
  # Spring MVC 相关配置
    mvc:
      view:
        prefix: /static/templates/
        suffix: .html
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/c2c_database?characterEncoding=UTF-8
        driver-class-name: com.mysql.jdbc.Driver
        # 使用druid数据源  L41Rp4v7CI
        type: com.alibaba.druid.pool.DruidDataSource
        username: root
        password: 123456

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql