package info.btsland.exchange.model;

public class Help {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column help.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column help.help_id
     *
     * @mbggenerated
     */
    private String helpId="";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column help.dealer_id
     *
     * @mbggenerated
     */
    private String dealerId="";

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help.id
     *
     * @return the value of help.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help.id
     *
     * @param id the value for help.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help.help_id
     *
     * @return the value of help.help_id
     *
     * @mbggenerated
     */
    public String getHelpId() {
        return helpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help.help_id
     *
     * @param helpId the value for help.help_id
     *
     * @mbggenerated
     */
    public void setHelpId(String helpId) {
        this.helpId = helpId == null ? null : helpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help.dealer_id
     *
     * @return the value of help.dealer_id
     *
     * @mbggenerated
     */
    public String getDealerId() {
        return dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help.dealer_id
     *
     * @param dealerId the value for help.dealer_id
     *
     * @mbggenerated
     */
    public void setDealerId(String dealerId) {
        this.dealerId = dealerId == null ? null : dealerId.trim();
    }
}